### ISSUE TITLE
Support the generation of OpenAPI3 parameter components

### ISSUE THREAD

**Issue by kabooboo** [exleym/Flask-Filter#21]
When documenting endpoints with openAPI (for instance with [APISpec](https://github.com/marshmallow-code/apispec)), it would be nice to have a way of adding OpenAPI parameter components to the API's specification.

This can be achieved by modifying the class FlaskFilter's constructor:

```python
# === base.py ===
# [...]
from flask_filter.spec import OPENAPI_SPEC
# [...]
class FlaskFilter(object):
    # [...]
    def openapi_spec(self, major=3, minor=0, patch=3):
        # Maybe we can add some logic here in order to get the closest higher version with the same major,
        # should the demanded version not exist
        return OPENAPI_SPEC[major][minor][patch]
        
# === spec.py ===
OPENAPI_SPEC = {
    # [...]
}
``` 

This could be used in Flask projects in the following way: 

```python
# spec = APISpec()

all(
    spec.components.parameter(parameter_name, parameter_value)
    for parameter_name, parameter_value in filtr.openapi_spec(major=3, minor=0, patch=1)
)
```
The code above would load into the spec object all the needed parameter components that can be referenced with `#/components/parameters/flaskFilter`

---

I'm not quite sure if this would belong in here, or as a [APISpec Plugin](https://apispec.readthedocs.io/en/latest/writing_plugins.html)...

**Comment by kabooboo** [comment]
Totally mistaken where the parameters were supposed to be. With parameters in body (`application/json`), it is up to the factory function to add the documentation to the generated `/search` endpoint, regardless of the Flask libraries used.

**Comment by exleym** [comment]
Cool, I was a little confused how OpenAPI spec fit into this. I've mostly been using this with [flask-restx](https://github.com/python-restx/flask-restx) and [flask-accepts](https://github.com/apryor6/flask_accepts) to autogen search endpoints for each resource like so:

```python
def generate_search_manager(api, namespace, Schema, Model, filtr, resource_name: str = None) -> type(Resource):
    resource_name = resource_name or Schema.__name__.replace("Schema", "")
    schema = Schema()

    @namespace.route("/search")
    class ResourceSearch(Resource):

        @namespace.doc(f"execute a resource search for {resource_name}")
        @accepts(schema=SearchSchema, api=api)
        @responds(schema=Schema(many=True), status_code=200, api=api)
        def post(self):
            filters = namespace.payload.get("filters")
            return filtr.search(
                DbModel=Model,
                filters=filters,
                ModelSchema=schema
            )

    return ResourceSearch
```

Obviously, there's still a lot to improve on here, but it keeps this library focused on a singular task, which allows it to stay fairly simple and straightforward.
